Repository EpitechMirror/Zappy, pull requests merged in 2025-06, with the labels that each got.

#36 Ai
  .github/workflows/ai-build.yml
  ai/src/__init__.py
  ai/src/ai.py
  ai/tests/__init__.py
  ai/tests/test_ai.py
Labels: bug

#41 Workflows edit
  .github/workflows/integration-test.yml
  ai/src/ai.py
  build.sh
  gui/CMakeLists.txt
  gui/renderer/Renderer.hpp
  server/CMakeLists.txt
  server/src/tmp.c
Labels: task

#40 Add TODO for level 8 info in ZappyAI and update test file permissions
  ai/src/Classes.py
  ai/src/MemorySystem.py
  ai/src/NeuralNetwork.py
  ai/src/ThinkingModule.py
  ai/src/ZappyAI.py
  ai/src/ai.py
  ai/src/main.py
  ai/tests/test_ai.py
Labels: invalid

#49 Gui
  gui/CMakeLists.txt
  gui/client/Client.cpp
  gui/main.cpp
  gui/map/Map.cpp
  gui/map/Map.hpp
  gui/renderer/Player/Player.cpp
  gui/renderer/Player/Player.hpp
  gui/renderer/Renderer.cpp
  gui/renderer/Renderer.hpp
  gui/tests/test_client.cpp
Labels: task

#55 Gui
  gui/CMakeLists.txt
  gui/client/Client.cpp
  gui/client/Client.hpp
  gui/client/ProtocolHandler.cpp
  gui/client/ProtocolHandler.hpp
  gui/main.cpp
  gui/map/Map.cpp
  gui/map/Map.hpp
  gui/renderer/Player/Player.cpp
  gui/renderer/Player/Player.hpp
  gui/renderer/Renderer.cpp
  gui/renderer/Renderer.hpp
  gui/tests/test_camera.cpp
  gui/tests/test_client.cpp
  gui/tests/test_light.cpp
  gui/tests/test_map.cpp
  gui/tests/test_player.cpp
  gui/tests/test_renderer.cpp
  gui/tests/test_shader.cpp
Labels: task

#66 Ai
  ai/src/Classes.py
  ai/src/main_ai.py
Labels: bug, enhancement

#74 Ai
  .github/workflows/ai-build.yml
  .github/workflows/code-quality.yml
  .github/workflows/dependency-check.yml
  .github/workflows/integration-test.yml
  ai/TEST_SUITE_SUMMARY.md
  ai/pytest.ini
  ai/requirements.txt
  ai/run_tests.py
  ai/src/NeuralNetwork.py
  ai/src/main_ai.py
  ai/test.sh
  ai/test_workflow.sh
  ai/tests/README.md
  ai/tests/test_ai.py
  ai/tests/test_classes.py
  ai/tests/test_main_ai.py
  ai/tests/test_memory_system.py
  ai/tests/test_neural_network.py
  ai/tests/test_thinking_module.py
  ai/tests/test_zappy_ai.py
Labels: documentation, enhancement
